name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Copy Artifact for integration test
        run: ./gradlew :functional-test:copyPluginArtifact
      - name: Run integration Test
        run: ./gradlew :functional-test:functionalTest
      - name: Get Release Version
        id: get_version
        run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: ansible-plugin-${{ steps.get_version.outputs.VERSION }}
          path: build/libs/ansible-plugin-${{ steps.get_version.outputs.VERSION }}.jar